micronaut:
  application:
    name: bookManagement
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/public/**"
        paths: "classpath:public"
  security:
    authentication: session
    endpoints:
      login:
        enabled: false
    redirect:
      login-success: /
      login-failure: /login/authFailed
      unauthorized:
        url: /login/
    intercept-url-map:
      - pattern: /public/**
        http-method: GET
        access:
          - isAnonymous()
  health:
    monitor:
      enabled: false
  views:
    thymeleaf:
      cacheable: false

datasources:
  default:
    url: 'jdbc:h2:mem:micronaut-sample;LOCK_TIMEOUT=10000;MODE=PostgreSQL'
    username: 'sa'
    password: ''
    driverClassName: 'org.h2.Driver'
    schema-generate: CREATE_DROP
    dialect: H2
flyway:
  datasources:
    default:
      locations: db/migration
